version: '1.0'

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: my_password
      MYSQL_DATABASE: keycloak_db
      MYSQL_USER: my_admin
      MYSQL_PASSWORD: my_password
    ports:
      - "3306:3306"
  keycloak:
    image: quay.io/keycloak/keycloak:legacy
    environment:
      DB_VENDOR: MYSQL
      DB_ADDR: mysql
      DB_DATABASE: keycloak_db
      DB_SCHEMA: public
      DB_USER: my_admin
      DB_PASSWORD: my_password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password
    ports:
      - "8080:8080"
    depends_on:
      - mysql